### ISSUE TITLE
识别建表语句报错

### ISSUE THREAD

**Issue by hutingfeng** [GooseCoding/utilsbox#1]
![image](https://user-images.githubusercontent.com/29219063/220501496-85e0e7ee-d031-4d70-8097-3f04a0e57b1f.png)

**Comment by GooseCoding** [comment]
请贴一下您的SQL语句

**Comment by GooseCoding** [comment]
应该是您的SQL建表语句格式不支持，请贴一下您的SQL建表语句，我看一下原因

**Comment by GooseCoding** [comment]
后续会优化这类空指针异常，不支持的语句直接报出明确的错误信息
