### ISSUE TITLE
这个工具非常方便，感谢分享！有个问题，如何配置生成mapper.xml里面的resultMap呢

### ISSUE THREAD

**Issue by danxibaozdh** [GooseCoding/utilsbox#5]
期待您的回复，谢谢
![Uploading image.png…]()

**Comment by GooseCoding** [comment]
代码模版配置 -> 选择您mapper对应的代码模版 -> 在主体代码块中，加入以下模版内容
` 
   <resultMap id="唯一的标识" type="xxx.$table_name_hump_A$">  
       $common_custom_code_block$
    </resultMap>
`

然后，在成员代码块中，添加 通用的动态代码块 (common_custom_code_block)
并且输入以下代码块模版内容：
` 
      <result column="$field_name$" property="$field_name_hump$" jdbcType="$field_type_jdbc$" javaType = "java.lang.$field_type_java$" /> 
`

确认保存，重新生成一下代码即可

**Comment by danxibaozdh** [comment]
我试试，谢谢您

在 2023-04-14 17:47:25，"大鹅coding" ***@***.***> 写道：


代码模版配置 -> 选择您mapper对应的代码模版 -> 在主体代码块中，加入以下模版内容
<resultMap id="唯一的标识" type="xxx.$table_name_hump_A$"> $common_custom_code_block$ </resultMap>

然后，在成员代码块中，添加 通用的动态代码块 (common_custom_code_block)
并且输入以下代码块模版内容：
<result column="$field_name$" property="$field_name_hump$" jdbcType="$field_type_jdbc$" javaType = "java.lang.$field_type_java$" />

确认保存，重新生成一下代码即可

**Comment by danxibaozdh** [comment]
“添加 通用的动态代码块 (common_custom_code_block)”

您好，动态代码块在哪里添加呢，找了半天没有找到呢
